#!/usr/bin/env node
// Flick Goal web copy for Capacitor (NO bundler, NO transpiling): copies the files the game needs
// into www/ (capacitor.config.json "webDir") and stamps the build profile into the COPY only.
//
//   node scripts/build-web.mjs [--profile dev|web-release|android-debug|android-release] [--ads test|live] [--out www]
//
// Copied: index.html, styles.css, icon.svg, manifest.webmanifest, src/** (tests, docs, sketches,
// scripts, node_modules, android/ are never copied). www/src/build-profile.js is REWRITTEN with the
// chosen profile; the committed src/build-profile.js (profile 'dev') is never touched.
// Default profile: android-debug (the common case for `npx cap sync`).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PROFILES = ['dev', 'web-release', 'android-debug', 'android-release'];
const ROOT_FILES = ['index.html', 'styles.css', 'icon.svg', 'manifest.webmanifest'];
const DIRS = ['src'];

function args(argv) {
  const out = { profile: 'android-debug', ads: 'test', out: 'www' };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const val = () => {
      const v = argv[++i];
      if (v == null || v.startsWith('--')) throw new Error(`${a} needs a value`);
      return v;
    };
    if (a === '--profile') out.profile = val();
    else if (a === '--ads') out.ads = val();
    else if (a === '--out') out.out = val();
    else if (a === '-h' || a === '--help') { out.help = true; }
    else throw new Error(`unknown argument: ${a}`);
  }
  return out;
}

function fail(msg) {
  console.error(`build-web: ${msg}`);
  process.exit(1);
}

let opt;
try { opt = args(process.argv.slice(2)); } catch (e) { fail(e.message); }
if (opt.help) {
  console.log('usage: node scripts/build-web.mjs [--profile ' + PROFILES.join('|') + '] [--ads test|live] [--out www]');
  process.exit(0);
}
if (!PROFILES.includes(opt.profile)) fail(`--profile must be one of ${PROFILES.join(', ')} (got "${opt.profile}")`);
if (opt.ads !== 'test' && opt.ads !== 'live') fail(`--ads must be test or live (got "${opt.ads}")`);
if (opt.ads === 'live' && opt.profile !== 'android-release') {
  fail('--ads live is only allowed with --profile android-release (debug builds always use Google test ads)');
}

const outDir = path.resolve(ROOT, opt.out);
const rel = path.relative(ROOT, outDir);
// Safety: only ever wipe a folder INSIDE the repo that is not a source folder.
if (!rel || rel.startsWith('..') || path.isAbsolute(rel) || ['src', 'tests', 'docs', 'android', 'scripts', 'node_modules', '.git'].includes(rel.split(path.sep)[0])) {
  fail(`refusing to write to ${outDir}`);
}

fs.rmSync(outDir, { recursive: true, force: true });
fs.mkdirSync(outDir, { recursive: true });

let files = 0;
function copyFile(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  files++;
}
function copyDir(from, to) {
  for (const ent of fs.readdirSync(from, { withFileTypes: true })) {
    if (ent.name.startsWith('.')) continue;
    const a = path.join(from, ent.name);
    const b = path.join(to, ent.name);
    if (ent.isDirectory()) copyDir(a, b);
    else if (ent.isFile()) copyFile(a, b);
  }
}

for (const f of ROOT_FILES) {
  const from = path.join(ROOT, f);
  if (!fs.existsSync(from)) fail(`missing ${f}`);
  copyFile(from, path.join(outDir, f));
}
for (const d of DIRS) copyDir(path.join(ROOT, d), path.join(outDir, d));

// Stamp the build profile into the copy (pure data module, same shape as the committed one).
const profileSrc = `// GENERATED by scripts/build-web.mjs for this build only. The committed src/build-profile.js stays 'dev'.
export const BUILD = Object.freeze({ profile: ${JSON.stringify(opt.profile)}, adMode: ${JSON.stringify(opt.ads)} });

export default BUILD;
`;
fs.writeFileSync(path.join(outDir, 'src', 'build-profile.js'), profileSrc);

console.log(`build-web: ${files} files -> ${rel}/ (profile ${opt.profile}, ads ${opt.ads})`);
